[#1319] fix(server): Add shaded com.google.guava:failureaccess dependency to prevent NoClassDefFoundError (#1352)
### What changes were proposed in this pull request?

Add shaded com.google.guava:failureaccess dependency in server pom.xml to prevent NoClassDefFoundError

### Why are the changes needed?

For [#1319](https://github.com/apache/incubator-uniffle/issues/1319)

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

By running server successfully.

(cherry picked from commit 1c7c40bf8963e8be9b400560f26a5d4b8a320fee)