Fix flaky test of ClientConfManagerTest (#260)
### What changes were proposed in this pull request?

For [https://github.com/apache/incubator-uniffle/actions/runs/3213433147/jobs/5253100348](https://github.com/apache/incubator-uniffle/actions/runs/3213433147/jobs/5253100348)
```Error:  dynamicRemoteByAppNumStrategyStorageTest  Time elapsed: 11.065 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <hdfs://host2/path2> but was: <hdfs://host3/path3>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
	at org.apache.uniffle.coordinator.ClientConfManagerTest.dynamicRemoteByAppNumStrategyStorageTest(ClientConfManagerTest.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at 
```
This is because scheduling thread didn't update the remote path timely. For this test, we will trigger update logic manually.

### Why are the changes needed?
Fix flaky test.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
UT passed.