[#770]  feat(cli): Introduce apache.commons.cli basic framework (#833)
### What changes were proposed in this pull request?

We use `apache.commons.cli` to add commands to `Uniffle`.  I created a command called `uniffle`, the following is the case of using the command.

> Case1: Use the uniffle command directly.
- uniffle / uniffle --help
```
Usage: uniffle [OPTIONS] SUBCOMMAND [SUBCOMMAND OPTIONS]
 or    uniffle [OPTIONS] CLASSNAME [CLASSNAME OPTIONS]
  where CLASSNAME is a user-provided Java class

  OPTIONS is none or any of:

--daemon (start|status|stop)   operate on a daemon

  SUBCOMMAND is one of:


    Admin Commands:

admin-cli    prints uniffle-admin args information

    Client Commands:

client-cli   prints uniffle-cli args information

SUBCOMMAND may print help when invoked w/o parameters or with -h.
```

> Case2: use a command that does not create.
- uniffle testadmin

```
ERROR: testadmin is not COMMAND nor fully qualified CLASSNAME.
DEBUG: UNIFFLE_SUBCMD_USAGE_TYPES accepted client
DEBUG: UNIFFLE_SUBCMD_USAGE_TYPES accepted admin
Usage: uniffle [OPTIONS] SUBCOMMAND [SUBCOMMAND OPTIONS]
 or    uniffle [OPTIONS] CLASSNAME [CLASSNAME OPTIONS]
  where CLASSNAME is a user-provided Java class

  OPTIONS is none or any of:

--daemon (start|status|stop)   operate on a daemon

  SUBCOMMAND is one of:


    Admin Commands:

admin-cli    prints uniffle-admin args information

    Client Commands:

client-cli   prints uniffle-cli args information

SUBCOMMAND may print help when invoked w/o parameters or with -h.
```

> Case3: Use the help command
- uniffle client-cli --help

```
Usage:
   Optional
     -a,--admin <arg>   This is an admin command that will print args.
     -c,--cli <arg>     This is an client cli command that will print args.
     -h,--help          Help for the Uniffle CLI.
```

> Case4:  Run the example-cli command
- uniffle  client-cli --cli test-cli

```
uniffle-client-cli : test-cli
```

### Why are the changes needed?

We use apache.commons.cli to add commands to Uniffle. 

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

- Unit test verification.
- Execute commands directly.

Co-authored-by: slfan1989 <louj1988@@>