[MINOR] test: fix CoordinatorGrpcTest#shuffleServerHeartbeatTest on Linux SSD platform (#738)
### What changes were proposed in this pull request?

Fix CoordinatorGrpcTest#shuffleServerHeartbeatTest on Linux SSD platform

### Why are the changes needed?

```
[INFO] Results:                                                                                                                     
[INFO]                                                                                                                              
[ERROR] Failures:                                                                                                                   
[ERROR]   CoordinatorGrpcTest.shuffleServerHeartbeatTest:240 expected: <HDD> but was: <SSD>                                         
[ERROR] Errors:                                                                                                                     
[ERROR]   CoordinatorGrpcTest.getShuffleAssignmentsTest:125 » Runtime No shuffle server ...                                         
[ERROR]   CoordinatorGrpcTest.rpcMetricsTest:274 » Runtime No shuffle server connected                                              
[INFO]                                                                                                                              
[ERROR] Tests run: 6, Failures: 1, Errors: 2, Skipped: 0                                                                            
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

```
[INFO] Running org.apache.uniffle.test.CoordinatorGrpcTest                                                                          
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.622 s - in org.apache.uniffle.test.CoordinatorGrpcTest    
[INFO]                                                                                                                              
[INFO] Results:                                                                                                                     
[INFO]                                                                                                                              
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0                                                                             
[INFO] 
```