[MINOR] improve(common/server/coordinator): Display the port in use port (#2122)
### What changes were proposed in this pull request?

Display the port while in use

### Why are the changes needed?

Help to find the in use port and its process.

### Does this PR introduce _any_ user-facing change?

```
16:29:02.179 [main] ERROR org.apache.uniffle.common.web.JettyServer - Terminating with exit status 1: Fail to start jetty http server, port is 9528
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_251]
	at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_251]
	at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_251]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_251]
```

### How was this patch tested?

UTs.