[#1844] fix(spark): Reassign shuffle servers when retrying stage (#1845)
### What changes were proposed in this pull request?

If the Shuffle Server is not reassigned after the Retry is triggered at the Stage, data will be lost. Therefore, reassign the Shuffle Server after the Retry.
question: 
Error:  Failures:  Error:    RSSStageDynamicServerReWriteTest.testRSSStageResubmit:119-SparkIntegrationTestBase.run:64->SparkIntegrationTestBase.verifyTestResult:149 expected: <1000> but was: <970>.

### Why are the changes needed?

Fix: #1844

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Presence test.