[#580] chore(ci): disable parallel build in maven (#631)
### What changes were proposed in this pull request?

Disable parallel build in maven

### Why are the changes needed?

CI crashed.

```
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 1
Error:  Crashed tests:
Error:  org.apache.uniffle.server.ShuffleServerTest
```

https://github.com/apache/incubator-uniffle/actions/runs/4220729609/jobs/7327285796#step:6:1317

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

CI.