[MINOR] fix: Error logs upload fail (#917)
### What changes were proposed in this pull request?

https://github.com/apache/incubator-uniffle/actions/runs/5141497645/jobs/9254329542?pr=916 fail, but error logs upload fail, so we can't analyze the cause.

Upload logs are below: 

```
Run actions/upload-artifact@v3
With the provided path, there will be 53 files uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Error: Artifact name is not valid: test-reports-mr:hadoop3.2. Contains the following character:  Colon :
          
Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n, Backslash \, Forward slash /
          
These characters are not allowed in the artifact name due to limitations with certain file systems such as NTFS. To maintain file system agnostic behavior, these characters are intentionally not allowed to prevent potential problems with downloads on different file systems.
```

### Why are the changes needed?

reproduce error describe in https://github.com/apache/incubator-uniffle/actions/runs/5141497645/jobs/9254329542?pr=916

Co-authored-by: zhengchenyu001 <zhengchenyu001@ke.com>